apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yolo
spec:
  selector:
    matchLabels:
      app: frontend-yolo
  template:
    metadata:
      labels:
        app: frontend-yolo
    spec:
      containers:
      - name: yolo-frontend 
        image: thandie/yolo-frontend:1.0.5
        ports:
        - containerPort: 80
