apiVersion: v1
kind: Service
metadata:
  name: frontend-yolo-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-yolo
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
